services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: app
    environment:
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      LUIGI_S3_ENDPOINT: http://minio:9000
      MLFLOW_TRACKING_URI: http://mlflow:5000
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      MLFLOW_ARTIFACT_URI: s3://mlflow-artifacts
      GIT_PYTHON_REFRESH: quiet
      PYSPARK_SUBMIT_ARGS: --conf spark.driver.extraJavaOptions=--add-opens=java.base/javax.security.auth=ALL-UNNAMED pyspark-shell
      JAVA_TOOL_OPTIONS: --enable-native-access=ALL-UNNAMED
      KAGGLEHUB_CACHE_DIR: /app/.cache/kagglehub
      HOME: /app
    ports:
      - "4040-4050:4040-4050"
      - "8082:8082"
    volumes:
      - .:/app
    depends_on:
      - minio_fs
      - mlflow
    networks:
      - ml_pr_network

  minio_fs:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    networks:
      - ml_pr_network

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    container_name: mlflow
    environment:
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
    command: [
      "mlflow", "server",
      "--backend-store-uri", "sqlite:///mlflow.db",
      "--default-artifact-root", "s3://mlflow-artifacts",
      "--host", "0.0.0.0"
    ]
    ports:
      - "5000:5000"
    depends_on:
      - minio_fs
    networks:
      - ml_pr_network

  loki:
    image: grafana/loki:2.9.14
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./volumes/loki:/tmp/loki
      - ./.docker/loki/config/loki-config.yaml:/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    depends_on:
      - minio_fs
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ml_pr_network

  promtail:
    image: grafana/promtail:2.9.14
    container_name: promtail
    command: -config.file=/etc/promtail/promtail.yaml
    volumes:
      - ./.docker/promtail/config/promtail-config.yaml:/etc/promtail/promtail.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/machine-id:/etc/machine-id:ro
    depends_on:
      - loki
    networks:
      - ml_pr_network

  grafana:
    image: grafana/grafana:11.5.3
    container_name: grafana
    user: "0:0"
    volumes:
      - ./volumes/grafana:/var/lib/grafana
      - ./.docker/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=grafana
      - GF_SECURITY_ADMIN_PASSWORD=grafana123
    depends_on:
      - loki
    networks:
      - ml_pr_network

volumes:
  minio_data:

networks:
  ml_pr_network:
    driver: bridge
